#
# Class information for RCP_SimpleMethod
#
# Generated by 'genprovider' for use with ruby-sfcc

require 'rubygems'
require 'cim'

module MOF
  class RCP_SimpleMethod
    METHODS = {
      "ReturnTrue" => { :type => :boolean }
    }
  end
end
