[ Description("Testing up-calls into the CIMOM from a provider")]
class Test_UpcallAtom
{

	[Description("Kickoff the method provider test")]
	string starttest(
	//return a string array of log messages
	);
	[Description("Send an export_indication")]
	uint16 send_indications(
	//return number of indications sent
	);
    [Description("Reset indication count")]
    uint16 reset_indication_count(
    // return 0
    );
    [Description("Get number of indications sent")]
    uint16 get_indication_send_count(
    // return number of indications sent since last reset
    );
};
[ Indication ]
class UpcallAtom_Indication : CIM_ProcessIndication
{
};
//class UpcallAtom_Indication_Handler : CIM_ListenerDestination
//{
//};






// Filter Instance
//INSTANCE OF CIM_IndicationFilter as $filter
//{
//    SystemCreationClassName = "OMC_UnitaryComputerSystem";
//    SystemName = "127.0.0.1";
//    CreationClassName = "CIM_IndicationFilter";
//    Name = "/UpcallAtom_Indication_Handler";
//    SourceNamespace = "root/cimv2";
//    Query = "select * from UpcallAtom_Indication";
//    QueryLanguage = "wql1";
//};

// Listener Destination Instance
//INSTANCE OF UpcallAtom_Indication_Handler as $dest
//{
//    SystemCreationClassName = "Linux_ComputerSystem";
//    SystemName = "npaxton1.provo.novell.com";
//    CreationClassName = "UpcallAtom_Indication_Handler";
//    Name = "/UpcallAtom_Indication_Handler";
//};

// Subscription Instance Tie together the indication filter
// and the indication handler
//INSTANCE OF CIM_IndicationSubscription
//{
//    Filter=$filter;
//    Handler=$dest;
//    AlertOnStateChange=false;
//};

